<?xml version="1.0" encoding="utf-8"?><Database Name="GuitarPick" Class="GuitarPickDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=BEAUDY-LAPTOP;Initial Catalog=GuitarPick;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GuitarPickConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Product" Member="ProductDOs">
    <Type Name="ProductDO" Id="ID1">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.Product_Get" Method="Product_Get">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.Product_GetList" Method="Product_GetList">
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.Product_InsertUpdate" Method="Product_InsertUpdate">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProductName" Parameter="productName" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="Price" Parameter="price" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
</Database>