<?xml version="1.0" encoding="utf-8"?><Database Name="GuitarPick" Class="GuitarPickContactDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=BEAUDY-LAPTOP;Initial Catalog=GuitarPick;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GuitarPickConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Contact" Member="ContactDOs">
    <Type Name="ContactDO">
      <Column Name="ContactID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.Contact_Insert" Method="Contact_Insert">
    <Parameter Name="ContactID" Parameter="contactID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="message" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(250)" />
    <Return Type="System.Int32" />
  </Function>
</Database>